### ISSUE TITLE
Some obvious places are not recognized

### ISSUE THREAD

**Issue by rhazegh** [mitmedialab/CLIFF#48]
I tried "Toronto" and it returns no results.

`curl http://localhost:8080/CLIFF-2.1.1/parse/text?q=Toronto`

``` json
{
    "milliseconds": 2,
    "results": {
        "organizations": [],
        "people": [],
        "places": {
            "focus": {},
            "mentions": []
        }
    },
    "status": "ok",
    "version": "2.1.1"
}
```

I also tried this on the demo here http://cliff.mediameter.org/ and got the same result:

<img width="826" alt="screenshot 2016-07-25 10 46 55" src="https://cloud.githubusercontent.com/assets/2200559/17105443/427de2b4-5255-11e6-94e5-5a9338ee1d7c.png">

**Comment by charlieg** [comment]
Geoparsing tools like CLIFF are designed to extract & resolve place names from complete sentences (e.g., try this as input: "I was born in Toronto and grew up in London."). If you're interested in extracting geographic information from partial addresses or fragments of text, you might have better luck with a geotagger.

**Comment by rhazegh** [comment]
I see. Thanks for the clarification. I parse whatever the user types in and try to extract the location. I wouldn't know if the user had entered just the location or had provided it within a phrase. 

Do you know of a geotagger that would be able to extract location from a fragment of text? Is there one that is case insensitive?
